baseURL = 'https://boolokam.com/'
languageCode = 'en-us'
title = 'Boolokam'
theme = "boolokam-theme"

# Site parameters
[params]
  description = "Boolokam News / Videos / Movies"
  author = "Boolokam"
  og_image = "images/og-image.jpg"
  
  # Social Media
  [params.social]
    twitter = "boolokam"
    facebook = "boolokam"
    instagram = "boolokam"
    youtube = "boolokam"

# RSS settings to limit file size
[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "index"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

# RSS Feed limits
[services.rss]
  limit = 100

# Menu configuration
[menu]
  # Main menu
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2
  [[menu.main]]
    name = "Videos"
    url = "/videos/"
    weight = 3
  [[menu.main]]
    name = "Movies"
    url = "/movies/"
    weight = 4

# Pagination
[pagination]
  postsPerPage = 9

# Specific section pagination
[params.pagination]
  newsPostsPerPage = 21

# Add global pagination settings
paginate = 21
paginatePath = "page"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  video_category = "video_categories"
  movie_genre = "movie_genres"

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# URL Management
[permalinks]
  categories = "/news/:slug/"
  
# Aliases
[params.aliases]
  "/categories/politics/" = "/news/politics/"
  "/categories/business/" = "/news/business/"
  "/categories/technology/" = "/news/technology/"
  "/categories/entertainment/" = "/news/entertainment/"
  "/categories/sports/" = "/news/sports/"
  "/categories/science/" = "/news/science/"
  "/categories/health/" = "/news/health/"

# Build optimization settings
[build]
  useResourceCacheWhen = "never"
  [build.buildStats]
    enable = false
  [[build.cachebusters]]
    source = "assets/.*"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*"
    target = "js"
  [[build.cachebusters]]
    source = "static/css/.*\\.css"
    target = "css"

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Cache-Control = "no-cache, no-store, must-revalidate"
      Pragma = "no-cache"
      Expires = "0"

[watch]
  [watch.pathspec]
    # Don't watch temporary files
    exclude = ["**/.git/**", "**/.hugo_build.lock", "**/node_modules/**", "**/.DS_Store", "**/.AppleDouble", "**/.LSOverride"]
  polling = true
  pollInterval = 2000 # 2 seconds instead of 1 second

# Resource cache settings
[caches]
  [caches.getjson]
    maxAge = "0s"
  [caches.getcsv]
    maxAge = "0s"
  [caches.images]
    maxAge = "0s"
  [caches.assets]
    maxAge = "0s"
  [caches.modules]
    maxAge = "0s"

# Output format configurations
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
